server {
    listen 80 default_server;
    server_name _;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 308 https://$host$request_uri;
    }
}

server {
    listen 443 ssl default_server;
    http2 on;
    server_name _;

    ssl_certificate /etc/letsencrypt/live/fly-print-cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fly-print-cloud/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;

    resolver 127.0.0.11 valid=10s ipv6=off;
    limit_conn per_ip_conn 20;
    limit_conn per_server_conn 500;

    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
    absolute_redirect off;

    include /etc/nginx/includes/application-locations.conf;
}
