server {
    listen 80 default_server;
    server_name _;

    resolver 127.0.0.11 valid=10s ipv6=off;
    limit_conn per_ip_conn 20;
    limit_conn per_server_conn 500;

    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
    absolute_redirect off;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    include /etc/nginx/includes/application-locations.conf;
}
